# Generated by Django 2.0.7 on 2018-07-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20180717_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='value',
        ),
    ]
