# Generated by Django 2.0.7 on 2018-07-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20180717_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_income',
        ),
        migrations.AddField(
            model_name='operation',
            name='is_income',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
